spring.application.name=TeamTaskManager
spring.jpa.hibernate.ddl-auto=update

# Database Configuration for Railway
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
server.port=${PORT:8080}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Dialect for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Useful for debugging in Railway logs
spring.jpa.show-sql=true
